repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: generate-readme
        name: Generate README
        entry: python generate-readme.py
        language: python
        pass_filenames: false
        files: ^images\.json$
